config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get "/newses" => 'articles#newses'
  get '/news/:id' => 'articles#news', as: :news

  #get '/articles/index' => 'articles#index'
  # get "/article_news/#{title}" => 'articles#clawl_news_show'

	resources :articles do
    resources :comments, only:[:create, :destroy]
  end
  post 'like/:comment_id' => 'likes#create', as: :like
  delete 'like/:comment_id' => 'likes#destroy', as: :likes
  root 'articles#newses'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
	has_many :comments
	belongs_to :user
end

app/models/comment.rb
class Comment < ApplicationRecord
	has_many :likes
	belongs_to :user
	belongs_to :article

	def like?(user)
		Like.where(user_id: user.id).present?
	end
end

app/models/genre.rb
class Genre < ApplicationRecord
end

app/models/like.rb
class Like < ApplicationRecord
	belongs_to :user
	belongs_to :comment
end

app/models/source.rb
class Source < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :likes
  has_many :comments
  has_many :articles

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
require 'nokogiri'
require 'open-uri'

class ArticlesController < ApplicationController
	before_action :clawling, only: [:news, :newses]
	def newses
		@entry_a = @clawl_news.xpath('//ul[@class="list-typeA"]').xpath('.//a')
	end

	def news
		@entry_list = @clawl_news.xpath('//ul[@class="list-typeA"]').xpath('.//li')
		id = params[:id].to_i
		@article = @entry_list[id]
		href = @article.children.to_ary
		href = href[1]
		href = href["href"]
		url = "https://mainichi.jp/#{href}"
		@clawl_new = Nokogiri::HTML.parse(open(url), nil, nil)
		@entry_title = @clawl_new.xpath('//article').xpath('.//header')
		@entry_body = @clawl_new.xpath('//article').xpath('.//p')
	end

	def new
		@article = Article.new
	end

	def create
		@article = Article.create(article_params)
		redirect_to article_path(@article)
	end

	def show
		@article = Article.find(params[:id])
	end

	def index
		@articles = Article.all
	end

	private
	def clawling
		url = 'https://mainichi.jp/'
		@clawl_news = Nokogiri::HTML.parse(open(url), nil, nil)
	end

	def article_params
		params.require(:article).permit(:title, :body, :user_id)
	end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def create
		@comment = Comment.new(comment_params)
		@comment.save

		redirect_to article_path(@comment.article_id)
	end

	private
	def comment_params
		params.require(:comment).permit(:body, :article_id, :user_id)
	end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
	def create
		comment = Comment.find_by(params[:comment_id])
		Like.create(comment_id: comment.id, user_id: current_user.id)
		redirect_to article_path(comment.article_id)
	end

	def destroy
		# binding.pry
		comment = Comment.find_by(params[:comment_id])
		like = Like.find_by(comment_id: comment.id, user_id: current_user.id)
		like.destroy
		redirect_to article_path(comment.article_id)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
	def url(model)
		url = article_url(model)
	end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/views/articles/index.html.erb
<h2>トークルーム一覧</h2>

<% @articles.each do |article| %>
	<div class="article-room">
		<%= article.title %>:
		<%= article.body %>
		<%= link_to "into", article_path(article) %>
	</div>
	<div>
		<% if user_signed_in? %>
			<% if article.user_id == current_user.id %>
				<%= link_to "削除", article_path(article), method: :delete %>
			<% end %>
		<% end %>
	</div>
<% end %>

app/views/articles/new.html.erb
<div class="talk-room-form">
	<%= form_for @article do |f| %>
		<p>
			<%= f.label :title %><br>
			<%= f.text_field :title, class: "form-control" %>について
		</p>
		<p>
			<%= f.label :body %><br>
			<%= f.text_field :body, class: "form-control" %>
			<%= f.hidden_field :user_id, value: current_user.id %>
		</p>
		<p>
			<%= f.submit "Create Room" %>
		</p>
	<% end %>
</div>

app/views/articles/news.html.erb
<%# binding.pry %>
<p id="article_<%= params[:id] %>">
<%= @entry_title.inner_html.html_safe %>
</p>

<p>
	<%= @entry_body.inner_html.html_safe %>
</p>

<% if user_signed_in? %>
<p>
<%= link_to "New Comment Room", new_article_path %>
</p>
<% else %>
<%= link_to "New Comment Room", new_user_session_path %>
<% end %>

app/views/articles/newses.html.erb
<%#binding.pry %>
  <% @entry_a.first(5).each_with_index do |entry, index| %>
  <p style="display: inline;">
  <%= link_to entry.inner_html.html_safe %>
  <p class="btn btn-default"><%= link_to "more", news_path(index) %></p>
  </p>
  <% end %>

app/views/articles/show.html.erb
<!-- Trigger the modal with a button -->
<div class="comment-modal">
	<% if user_signed_in? %>
		<button type="button" class="btn btn-info btn-lg" data-toggle="modal" data-target="#myModal">
			<span class="glyphicon glyphicon-comment"></span>
		</button>
	<% end %>
</div>

<!-- Modal -->
<div id="myModal" class="modal fade" role="dialog">
    <div class="modal-dialog">
      <!-- Modal content-->
        <div class="modal-content">
	            <%= form_for Comment.new, url: article_comments_path(@article.id) do |f| %>
	        <div class="modal-header">
	          	<button type="button" class="close" data-dismiss="modal">&times;</button>
	          	<h4 class="modal-title"><%= f.label :body, "コメント" %></h4>
	        </div>
	        <div class="modal-body">
	          	<p><%= f.text_area :body, class: "form-control", id: "comment" %>
	          		<%= f.hidden_field :user_id, value: current_user.id %>
			  		<%= f.hidden_field :article_id, value: @article.id %>
			  	</p>
	        </div>
	        <div class="modal-footer">
	          	<%= f.submit "コメント" %>
	        </div>
	        <% end %>
      	</div>
    </div>
</div>

<!-- ここから本文 -->
<!-- 討論する議題  -->
<article class="show-article">
	<div>
		<h1><%= @article.title %>について</h1>
	</div>
	<p>
		<%= @article.body %>
	</p>
</article>

<hr>

<!-- 議題に対するコメント -->
<div class="comments-index clearfix">
	<% @article.comments.each do |comment| %>
		<div class="comments-user">
			<div class="user">
				<p class="user-icon">
					<span class="glyphicon glyphicon-user"></span>
				</p>
				<p>
					<%= comment.user.email %>
				</p>
			</div>
		</div>
		<div class="comment-body arrow_box">
			<p>
				<%= comment.body %>
			</p>
			<div class="like-btn">
				<% if user_signed_in? %>
					<% if comment.like?(current_user) %>
						<%= link_to likes_path(comment.id), method: :delete do %>
							<i class="fa fa-heart" aria-hidden="true"></i>
						<% end %>
					<% else %>
						<%= link_to like_path(comment.id), method: :post do %>
							<i class="fa fa-heart-o" aria-hidden="true"></i>
						<% end %>
					<% end %>
				<% end %>
			</div>
		</div>
	<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EagleEye</title>
    <%= csrf_meta_tags %>


    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<header>
		<h1>EagleEye</h1>
	</header>
	<div class="col-md-1"></div>
	<div class="col-md-9">
    <%= yield %>
    </div>
    <div class="col-md-1"></div>
  </body>
</html>